FROM lindajineth/miprimerdocker:lindaflyservices

# Set the JBOSS_HOME env variable
ENV JBOSS_HOME /opt/jboss/wildfly-8.2.1.Final

RUN echo "JAVA_OPTS=\"\$JAVA_OPTS -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0\"" >> $JBOSS_HOME/bin/standaleone.conf

# Expose the ports we're interested in 
EXPOSE 8080 9990

ENTRYPOINT $JBOSS_HOME/bin/standalone.sh



#CMD ["/opt/jboss/wildfly-8.2.1.Final/bin/standalone.sh", "-b", "0.0.0.0"]
