FROM lindajineth/miprimerdocker:lindaflyservices

# Set the WILDFLY_VERSION env variable
ENV WILDFLY_VERSION 8.2.0.Final

# Set User Jboss
USER  jboss
# Set the JBOSS_HOME env variable
ENV JBOSS_HOME /opt/jboss/wildfly-8.2.1.Final

# Expose the ports we're interested in
EXPOSE 8080 9990

#Deploy App LindaServices 
RUN cd /opt/jboss/wildfly-8.2.1.Final/standalone/deployments/ && curl -O  -sL  https://github.com/lindajineth/LindaServices/raw/b98aaa603fc14d2ee01a75567a0fb792c6b5aa1a/HolaMundoEAR.ear

# Set the default command to run on boot
# This will boot WildFly in the standalone mode and bind to all interface
CMD ["/opt/jboss/wildfly-8.2.1.Final/bin/standalone.sh", "-b", "0.0.0.0"]


